name: .NET

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - LICENSE
      - README.md
      - .gitignore
      - '**.sln'
      - '**.csproj**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - LICENSE
      - README.md
      - .gitignore
      - '**.sln'
      - '**.csproj**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Install CounterStrikeSharp.API
        run: dotnet add CenterSpeed.csproj package CounterStrikeSharp.API --version 1.0.328

      - name: Build
        run: dotnet build CenterSpeed.csproj --no-restore --configuration Release

      - name: Prepare artifact output folder
        run: |
          mkdir CenterSpeed
          cp bin/Release/net8.0/CenterSpeed.dll CenterSpeed/
          cp bin/Release/net8.0/CenterSpeed.pdb CenterSpeed/
          cp bin/Release/net8.0/CenterSpeed.deps.json CenterSpeed/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CenterSpeed
          path: CenterSpeed
